
spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      name: ${job.name:NONE}
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mysql://localhost:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

